### ISSUE TITLE
Wrong `Functions defined` in Java project

### ISSUE THREAD

**Issue by defool** [agentzh/code2ebook#4]
![qq 20150115154517](https://cloud.githubusercontent.com/assets/5835688/5754016/9f7e31ce-9ccd-11e4-96e3-bf857ddf8025.png)

Should we need a  `--language` option to deal with different languages' syntax?

**Comment by agentzh** [comment]
@defool Languages are automatically detected and handled by the `Exuberant  ctags` command-line utility. If the "defined functions" are wrong, then it's most likely to be your `ctags` program's fault. What version of `ctags` are you using? Better provide a minimal Java code example so that I can try out on my side.

**Comment by defool** [comment]
I use the latest version of `ctags` in Ubuntu14.04. The problem is that the meanings of `kinds` may be different in different language defined by `ctags`. For instance, `f' means function in `C` but means fields in `java`. `ctags --list-kinds` will list all meanings of kinds of different language.

So I'm not sure  whether it's necessary to use `--language` option (or auto detect) to deal with different languages' syntax.

**Comment by agentzh** [comment]
@defool I see. Yeah, it seems that we have to parse the `ctags --list-kinds=LANG` output every time we see a new language name, or just parse the output of `ctags --list-kinds=all` at the beginning.

Will you contribute a patch in a pull request?

Thanks!

**Comment by defool** [comment]
@agentzh Yes. I thank the references, like `macro_by_files`, should not be pre-defined. Instead,  every kinds of references in `ctags --list-kinds=all ` should be dynamic generated(and listed in html page) according to the kinds generated by `ctags`. 
What the bad is that I have to learn perl programming before I do this :)

**Comment by agentzh** [comment]
@defool No, listing all the "kinds" at the HTML page head is too overwhelming, especially for "fields" and "local variables", which is just not so interesting. I prefer only listing the most important kinds.

**Comment by defool** [comment]
@agentzh The kind of reference can be turned off in `ctags` if you don't want to show it in the HTML page. Please review my pull request. 
I am a beginner in github. Any suggestions are always welcome.

**Comment by ryderkun** [comment]
Hi,agentzh,i like reading,but i encounter the problem in the using the tool.

Specific error：
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
processing "." with ctags...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
failed to run command "ctags --exclude='*.html' --exclude='*.htm' -f ./src2html.tags -n -u --fields=kl -R '.'": 256

I don't know how to solve the problem   ^ . ^

**Comment by defool** [comment]
@ryderkun That seems to be the problem in `ctags`. Try to upgrade `ctags` to the latest version.

**Comment by ryderkun** [comment]
@defool I give up using the ctags of Xcode and i install the ctags by homebrew,success, thank you very much...@agentzh thx
