### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by vonnyfly** [agentzh/code2ebook#9]
$ /root/code2ebook/src2html.pl --tab-width 4 --color --cross-reference \            1 ↵
            --navigator --line-numbers . 'Linux 3.16.7' --exclude arch --exclude fs
processing "." with ctags...
failed to fork for command "vim -E -X -R -u ~/.vimrc -i NONE -c 'syntax on|source /root/code2ebook/syntax-highlight.vim|visual|call AnsiHighlight("/tmp/root/KNE57R4GS5")|q' --  sound/sparc/cs4231.c": Cannot allocate memory

 $ free -h
             total       used       free     shared    buffers     cached
Mem:          3.9G       1.7G       2.1G        22M        51M       1.2G
-/+ buffers/cache:       474M       3.4G
Swap:           0B         0B         0B

**Comment by agentzh** [comment]
@vonnyfly The --color option is a memory hog right now. You can either remove that option or find a bigger machine.

**Comment by vonnyfly** [comment]
Thanks, this tip sounds good.
